#===- lib/CSE231/analysis-framework-tests/Makefile -----------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../../..
LIBRARYNAME = CSE231Tests
LOADABLE_MODULE = 0

include $(LEVEL)/Makefile.common

